# Assignment5 </br>
### Orly Olbum </br>


## SC:py3, on page 448, try number 2a

### Find the SVD of A using numpy.linalg.svd.

In [15]:
import numpy as np

matrix = np.matrix([[10, 22, 32, 31, 41, 1, 0, 0, 1, 0], [8, 9, 13, 11, 10, 1, 0, 0, 0, 0], [56, 22, 39, 88, 19, 0, 0, 1, 2, 3], [0, 0, 1, 2, 0, 12, 13, 10, 14, 18], [1, 2, 0, 1, 0, 29, 33, 15, 20, 32], [0, 1, 0, 0, 1, 23, 34, 22, 2, 15]])
print(matrix)

U, S, V = np.linalg.svd(matrix)
print(U)
print(S)
print(V)

[[10 22 32 31 41  1  0  0  1  0]
 [ 8  9 13 11 10  1  0  0  0  0]
 [56 22 39 88 19  0  0  1  2  3]
 [ 0  0  1  2  0 12 13 10 14 18]
 [ 1  2  0  1  0 29 33 15 20 32]
 [ 0  1  0  0  1 23 34 22  2 15]]
[[-0.43576263 -0.02323797  0.86414503 -0.03919043  0.15317141  0.19449147]
 [-0.1667163  -0.00634615  0.1932772   0.01215241 -0.60048838 -0.7576776 ]
 [-0.88314102 -0.04057992 -0.46241801  0.02975314  0.03256587  0.05137121]
 [-0.02678926  0.3593577  -0.02079356 -0.4363243   0.64133929 -0.51770362]
 [-0.03594863  0.73245011 -0.01565606 -0.41311669 -0.42726813  0.3297817 ]
 [-0.01919838  0.57632619  0.03727449  0.79773861  0.14497432 -0.09319718]]
[128.77949883  80.71692702  38.33651053  18.88900087   5.33387396
   4.08482174]
[[-0.42850922 -0.2376731  -0.39277218 -0.72331744 -0.28212805 -0.01869881
  -0.01698492 -0.016405   -0.02589281 -0.03548672]
 [-0.02258726  0.00718706 -0.02538964 -0.03605256 -0.01500194  0.48043533
   0.60009215  0.33721458  0.25680195  0.47610825]
 [-0.41014158  0.27

### Truncate the SVD to only the top 2 eigenvectors (k=2), and plot the latent “coordinates” of each of the 6 documents. Use a different color or plotting symbol for the first 3 documents than the last 3.

In [18]:
print(S[0:2])

[128.77949883  80.71692702]


### Print out the truncated versions of U, S (sigma) and V. Describe in words what they mean and how they related the original document term matrix to your plot.

### Extra-credit: use non-negative matrix factorization on the same problem above, compare the output of SVD and non-negative matrix factorization in this case.